sudo: required
services:
  - docker

before_install:
  - docker build -t vladimir44/ci-cd -f Dockerfile.dev .

script:
  - docker run vladimir44/ci-cd npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "ci-cd"
  env: "CiCd-env"
  bucket_name: "elasticbeanstalk-us-east-2-181410295797"
  bucket_path: "ci-cd"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY